### ISSUE TITLE
support for parameterized strings?

### ISSUE THREAD

**Issue by richardpenner** [alexanderwallin/node-gettext#26]
Any plans to support string parameterization? For example [i18n-abide](https://github.com/mozilla/i18n-abide) supports the following syntax:
```req.gettext('Hello %(username)s', {username: 'johnsmith'});```
That named parameter helps provide context to translators.

**Comment by Dexus** [comment]
You can use something like sprintf look for it on NPM

**Comment by ArmorDarks** [comment]
In fact, you can use any templating language for this, including lodash templates.

However, original gettext indeed uses `sprintf` and I personally would recommend it too, because it's much more suitable for templating exactly l10n strings.

Here is the most popular version: https://github.com/alexei/sprintf.js

Just import it in you project, and wrap any l10n string you need with it. It's the same way as original GNU gettext handles it.

``` js
sprintf(gettext('Hello %(name)s'), 'Test')
```

**Comment by alexanderwallin** [comment]
Agreeing with answers and closing.
